application:
  id: gamification
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /gamification/v1
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration