CREATE TABLE CUSTOMER_EVENTS(
sys_id NUMERIC AUTO_INCREMENT PRIMARY KEY,
customer_number VARCHAR (50) NOT NULL,
goal_id NUMERIC NOT NULL,
CONSTRAINT GOAL_ID_FK FOREIGN KEY (goal_id) REFERENCES GOALS(goal_id)
);